name: Rust Example

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: simonsso/rust-action@master
        with:
          args: cargo fmt -- --check && cargo tarpaulin -o html

